# based on https://docs.dagger.io/1201/ci-environment

name: docker

on:
  push:
    branches:
      - main

jobs:
  dagger:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Build and push to ghcr
        uses: dagger/dagger-for-github@v3
        with:
          version: 0.2
          cmds: |
            project update
            do push
        env:
          REGISTRY_USER: _token_
          REGISTRY_PASS: ${{ secrets.GITHUB_TOKEN }}
